#!/usr/bin/env python3

import json, requests
from pprint import pprint
import sys

r = requests.get(url='http://pokeapi.co/api/v1/pokemon/' + sys.argv[1])
data = json.loads(r.text)

# pprint(data)
print('Name: '+ data["name"])
print('speed: ' + str(data['speed']))
print('defense: ' + str(data['defense']))
print('attack: ' + str(data['attack']))
print('hp: ' + str(data['hp']))
print('total: ' + str(data['total']))
for move in data['moves']:
    print(move['name'], end=', ')
